// <auto-generated />
using CheeseRecordsStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CheeseRecordsStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260801033109_AgregarAudioBeat")]
    partial class AgregarAudioBeat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CheeseRecordsStore.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistaId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.ToTable("Albumes");
                });

            modelBuilder.Entity("CheeseRecordsStore.Models.Artista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreArtistico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artistas");
                });

            modelBuilder.Entity("CheeseRecordsStore.Models.Beat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlbumId")
                        .HasColumnType("integer");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<int?>("GeneroId")
                        .HasColumnType("integer");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Letra")
                        .HasColumnType("text");

                    b.Property<int?>("LicenciaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombresArtistas")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("GeneroId");

                    b.HasIndex("LicenciaId");

                    b.ToTable("Beats");
                });

            modelBuilder.Entity("CheeseRecordsStore.Models.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("CheeseRecordsStore.Models.Licencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Licencias");
                });

            modelBuilder.Entity("CheeseRecordsStore.Models.Album", b =>
                {
                    b.HasOne("CheeseRecordsStore.Models.Artista", "Artista")
                        .WithMany("Albumes")
                        .HasForeignKey("ArtistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artista");
                });

            modelBuilder.Entity("CheeseRecordsStore.Models.Beat", b =>
                {
                    b.HasOne("CheeseRecordsStore.Models.Album", "Album")
                        .WithMany("Beats")
                        .HasForeignKey("AlbumId");

                    b.HasOne("CheeseRecordsStore.Models.Genero", "Genero")
                        .WithMany("Beats")
                        .HasForeignKey("GeneroId");

                    b.HasOne("CheeseRecordsStore.Models.Licencia", "Licencia")
                        .WithMany("Beats")
                        .HasForeignKey("LicenciaId");

                    b.Navigation("Album");

                    b.Navigation("Genero");

                    b.Navigation("Licencia");
                });

            modelBuilder.Entity("CheeseRecordsStore.Models.Album", b =>
                {
                    b.Navigation("Beats");
                });

            modelBuilder.Entity("CheeseRecordsStore.Models.Artista", b =>
                {
                    b.Navigation("Albumes");
                });

            modelBuilder.Entity("CheeseRecordsStore.Models.Genero", b =>
                {
                    b.Navigation("Beats");
                });

            modelBuilder.Entity("CheeseRecordsStore.Models.Licencia", b =>
                {
                    b.Navigation("Beats");
                });
#pragma warning restore 612, 618
        }
    }
}
